# Generated by Django 4.2.23 on 2025-08-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcompetence',
            name='pid',
            field=models.CharField(blank=True, help_text='Patient/Participant ID', max_length=50, null=True),
        ),
    ]
