# Generated by Django 4.2.23 on 2025-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitday',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Additional comments'),
        ),
        migrations.AddField(
            model_name='visitday',
            name='improvements',
            field=models.ManyToManyField(blank=True, related_name='improvements_of_day', to='mentorship.assignedcompetence'),
        ),
        migrations.AddField(
            model_name='visitday',
            name='strengths',
            field=models.ManyToManyField(blank=True, related_name='strengths_of_day', to='mentorship.assignedcompetence'),
        ),
        migrations.AlterField(
            model_name='assignedcompetence',
            name='mentor_grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Needs Improvement'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True),
        ),
    ]
