# Generated by Django 4.2.23 on 2025-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_visitday_comments_visitday_improvements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitday',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='strengths',
        ),
        migrations.AddField(
            model_name='visitday',
            name='improvements',
            field=models.TextField(blank=True, null=True, verbose_name='Skills needing mentoring/training'),
        ),
        migrations.AddField(
            model_name='visitday',
            name='strengths',
            field=models.TextField(blank=True, null=True, verbose_name='Main skills/areas of competency'),
        ),
    ]
