# Generated by Django 4.2.23 on 2025-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
