# Generated by Django 4.2.23 on 2025-08-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_remove_visitday_improvements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitday',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='visitday',
            name='strengths',
        ),
        migrations.AddField(
            model_name='visitday',
            name='improvements',
            field=models.ManyToManyField(blank=True, related_name='improvements_of_day', to='mentorship.assignedcompetence'),
        ),
        migrations.AddField(
            model_name='visitday',
            name='strengths',
            field=models.ManyToManyField(blank=True, related_name='strengths_of_day', to='mentorship.assignedcompetence'),
        ),
    ]
