# Generated by Django 4.2.23 on 2025-08-26 00:56

from django.db import migrations, models
import mentorship.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_remove_visitday_improvements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteeGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='MentorGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['score'],
            },
        ),
        migrations.AlterField(
            model_name='assignedcompetence',
            name='mentee_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name=mentorship.models.MenteeGrade),
        ),
        migrations.AlterField(
            model_name='assignedcompetence',
            name='mentor_grade',
            field=models.IntegerField(blank=True, null=True, verbose_name=mentorship.models.MentorGrade),
        ),
    ]
