# Generated by Django 4.2.23 on 2025-08-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_menteegrade_mentorgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcompetence',
            name='mentee_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorship.menteegrade'),
        ),
        migrations.AlterField(
            model_name='assignedcompetence',
            name='mentor_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mentorship.mentorgrade'),
        ),
    ]
